### ISSUE TITLE
Just a question...

### ISSUE THREAD

**Issue by vladBaciu** [tum-ei-eda/mlonmcu#117]
Can custom models and datasets be used easily on this project ?

I am wondering if I can evaluate a custom model on a custom dataset that is not publicly available. If yes, could you give me some hints ?

**Comment by PhilippvK** [comment]
The [model zoo ](url)we provide is entirely optional. There are a few ways to use your own models instead

- Just pass a relative/absolute path to the model file to the `mlonmch flow ...` command.
- Add your model you the user-level model directory, e.g. `~/.config/mlonmcu/models"
- Extend the model lookup paths in your `environment.yml` with any custom directories like this:
```yaml
paths:
  models:
    - "/work/git/mlonmcu/models"
    - "/home/ga87puy/.config/mlonmcu/models"
    - "/path/to/model/zoo"
``` 

The only limitation is that your model type has to be supported by one of mlonmcus frontends.

Regarding datasets: Since mlonmcu is only working with pre-trained models, it does not really care about datasets. The only case when the data becomes relevant is when validation the model outputs against a golden reference. This feature is supported by MLonMCU (see https://github.com/tum-ei-eda/mlonmcu/blob/main/ipynb/Examples/ValidateOutputs.ipynb) but we are currently working on a more sophisticated solution for model output verification...

I hope this answers your question!
