### ISSUE TITLE
Static Memory Usage - Update ELF sections

### ISSUE THREAD

**Issue by PhilippvK** [tum-ei-eda/mlonmcu#24]
For calculating the static ROM/RAM usage on non-ETISS targets, I have created `mlonmcu/target/elf.py` heavily inspired by ETISS `get_metrics.py`.

However as we are now also targeting ARM and x86 we will very likely miss some important ELF sections.

**Comment by PhilippvK** [comment]
I tried to map all of those in `elf.py`.

@rafzi What do you think about `.iram.text`, `.iram.data` and `.iram.bss`? Code could be split up over flash and instruction RAM, so should be still add `.iram.text` to `rom_code`?

**Comment by rafzi** [comment]
I'm not sure how the flash and boot process works for these. I guess text and data need to be stored in full in flash and then text would be loaded into iram during boot? The bss would not need storage space, but I assume it still has to occupy its whole space, because there would otherwise not be any information about it
